# This is a basic workflow that is manually triggered

name: Hola Mundo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
jobs:
  hola-mundo:
     runs-on: ubuntu-latest
     steps:
     - name: Send greeting
       run: echo "Hola Mundo"
